apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.{{ .Values.groupName }}
  labels:
    app: {{ include "webhook-dnsendpoint.name" . }}
    chart: {{ include "webhook-dnsendpoint.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: {{ .Values.groupName }}
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: {{ include "webhook-dnsendpoint.fullname" . }}
    namespace: {{ .Release.Namespace }}
  version: v1alpha1
