name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "charts/**"

permissions:
  contents: read
  packages: write

env:
  HELM_VERSION: 3.17.2

jobs:
  release-charts:
    name: Release chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.12.0
        with:
          setup-tools: |
            helmv3
          helm: "${{ env.HELM_VERSION }}"

      - name: Package Helm Charts
        shell: bash
        env:
          SRC_DIR: "charts"
          DEST_DIR: "dest"
          CHART: "webhook-dnsendpoint"
          REGISTRY: oci://ghcr.io/${{ github.repository_owner }}/charts
        run: |
          export VERSION=$(yq .version "${SRC_DIR}/${CHART}/Chart.yaml")

          helm dep up "${SRC_DIR}/${CHART}"
          helm package "${SRC_DIR}/${CHART}" -u -d "${DEST_DIR}"
          helm push "${DEST_DIR}/${CHART}-${VERSION}.tgz" "${REGISTRY}"
